### ISSUE TITLE
Problem start server

### ISSUE THREAD

**Issue by globsecure** [hnordt/reax#14]
After commands of readme.

15:13:33-[Mac:GlobSecure@reax]$ >> webpack -p
Hash: c4b44a57125e291902ea
Version: webpack 1.12.11
Time: 7188ms
    Asset    Size  Chunks             Chunk Names
bundle.js  347 kB       0  [emitted]  main
    + 319 hidden modules

WARNING in bundle.js from UglifyJs
Condition always true [./~/react/lib/ReactMount.js:764,0]
Condition always true [./~/react/lib/findDOMNode.js:46,0]
Condition always true [./~/react/lib/instantiateReactComponent.js:80,0]
Dropping unreachable code [./~/react/lib/shouldUpdateReactComponent.js:40,0]
Condition always true [./~/react/lib/traverseAllChildren.js:158,0]
Condition always true [./~/react-router/lib/Redirect.js:93,0]
Side effects in initialization of unused variable _active [./~/redux-form/lib/reducer.js:75,0]
Side effects in initialization of unused variable asyncError [./~/redux-form/lib/reducer.js:98,0]
Side effects in initialization of unused variable submitError [./~/redux-form/lib/reducer.js:99,0]
Side effects in initialization of unused variable touched [./~/redux-form/lib/reducer.js:207,0]
Side effects in initialization of unused variable isEmpty [./~/@hnordt/reax-validator/index.js:14,0]
Side effects in initialization of unused variable contains [./~/@hnordt/reax-validator/index.js:18,0]
Condition always true [./~/history/lib/createMemoryHistory.js:69,0]
Condition always true [./~/react-router/lib/IndexRedirect.js:58,0]
Condition always true [./~/react-router/lib/IndexRoute.js:55,0]
Condition always true [./~/react-router/lib/Route.js:50,0]
Condition always true [./~/react/lib/ReactDOMComponent.js:907,0]
Dropping side-effect-free statement [./~/react/lib/ReactEventListener.js:72,0]
Dropping unused function handleTopLevelWithPath [./~/react/lib/ReactEventListener.js:98,0]
Dropping unused variable DOCUMENT_FRAGMENT_NODE_TYPE [./~/react/lib/ReactEventListener.js:26,0]
Side effects in initialization of unused variable addArrayValue [./~/redux-form/lib/createHigherOrderComponent.js:183,0]
Side effects in initialization of unused variable asyncBlurFields [./~/redux-form/lib/createHigherOrderComponent.js:184,0]
Side effects in initialization of unused variable blur [./~/redux-form/lib/createHigherOrderComponent.js:185,0]
Side effects in initialization of unused variable change [./~/redux-form/lib/createHigherOrderComponent.js:186,0]
Side effects in initialization of unused variable focus [./~/redux-form/lib/createHigherOrderComponent.js:188,0]
Side effects in initialization of unused variable initialValues [./~/redux-form/lib/createHigherOrderComponent.js:191,0]
Side effects in initialization of unused variable onSubmit [./~/redux-form/lib/createHigherOrderComponent.js:193,0]
Side effects in initialization of unused variable removeArrayValue [./~/redux-form/lib/createHigherOrderComponent.js:196,0]
Side effects in initialization of unused variable returnRejectedSubmitPromise [./~/redux-form/lib/createHigherOrderComponent.js:197,0]
Side effects in initialization of unused variable startAsyncValidation [./~/redux-form/lib/createHigherOrderComponent.js:198,0]
Side effects in initialization of unused variable startSubmit [./~/redux-form/lib/createHigherOrderComponent.js:199,0]
Side effects in initialization of unused variable stopAsyncValidation [./~/redux-form/lib/createHigherOrderComponent.js:200,0]
Side effects in initialization of unused variable stopSubmit [./~/redux-form/lib/createHigherOrderComponent.js:201,0]
Side effects in initialization of unused variable submitFailed [./~/redux-form/lib/createHigherOrderComponent.js:202,0]
Side effects in initialization of unused variable swapArrayValues [./~/redux-form/lib/createHigherOrderComponent.js:203,0]
Side effects in initialization of unused variable validate [./~/redux-form/lib/createHigherOrderComponent.js:206,0]
Side effects in initialization of unused variable reduxMountPoint [./~/redux-form/lib/createReduxFormConnector.js:60,0]
Side effects in initialization of unused variable destroyOnUnmount [./~/redux-form/lib/createReduxFormConnector.js:61,0]
Side effects in initialization of unused variable form [./~/redux-form/lib/createReduxFormConnector.js:62,0]
Side effects in initialization of unused variable getFormState [./~/redux-form/lib/createReduxFormConnector.js:63,0]
Side effects in initialization of unused variable touchOnBlur [./~/redux-form/lib/createReduxFormConnector.js:64,0]
Side effects in initialization of unused variable touchOnChange [./~/redux-form/lib/createReduxFormConnector.js:65,0]
Condition always true [./~/validator/validator.js:25,0]
Dropping unreachable code [./~/validator/validator.js:27,5]
15:13:42-[Mac:GlobSecure@reax]$ >>

**Comment by hnordt** [comment]
The command `webpack -p` is used to create the `bundle.js` in `public/src` for production.

The warnings are normal, you can ignore them.

**Comment by globsecure** [comment]
Of course!
I really dumb. :)

PT: Boa rapaz! vamos ver como funciona agora hehe!

15:25:36-[Mac:GlobSecure@reax]$ >> webpack-dev-server --content-base public/ --inline --history-api-fallback
http://localhost:8080/
webpack result is served from /
content is served from /Users/GlobSecure/Nordth/reax/public
404s will fallback to /index.html
Hash: 4ca005283d7d944fce48
Version: webpack 1.12.11
Time: 2724ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.32 MB       0  [emitted]  main
chunk    {0} bundle.js (main) 1.24 MB [rendered]
    [0] multi main 40 bytes {0} [built]
